name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.snehatrimukhe134E }}
        password: ${{ secrets.Snehavt@123 }}

    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-snehatrimukhe135/wisecow-app:latest .
        docker push your-dockerhub-snehatrimukhe135/wisecow-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.20.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
